### ISSUE TITLE
Bug: TokenVotingSetup data size bigger than allowed

### ISSUE THREAD

**Issue by Ybittan** [aragon/osx#328] opened 2023-03-09 17:59 UTC
**Describe the bug**
I am getting an error on tokenvotingsetup contract that data size is bigger than allowed
(screenshot below)

**To Reproduce (please complete the following information)**
- Config and flags: completed the deploy checklist and am deploying to goerli (but have run into this on another custom chain as well)
- Steps to reproduce the behavior:
    yard deploy --network goerli

**Current behavior**
In depth explanation, if required, or a clear and concise description of what actually happens.

![image](https://user-images.githubusercontent.com/31249213/224113999-6d18145d-480b-4e02-987b-24c025531b5b.png)

**Expected behavior**
Contract should deploy

**System (please complete the following information):**
 - OS: Windows 10
 - Commit hash a362749d

**Comment by mathewmeconry** [comment] 2023-03-23 09:16
Hi @Ybittan 
Sorry that it took us so long to answer...
I assume you are using a custom RPC and not an externally provided one like Infura?

The error looks to me that you exceed the max body size for the HTTP request, this is indicated by the origin of the error:
`[...] ProviderError: HttpProviderError [...]`

**Comment by mathewmeconry** [comment] 2023-04-04 16:28
Closing it in house keeping. If you think the issue is still relevant please reopen it

**Closed by mathewmeconry** 2023-04-04 16:28 UTC
